// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import type { ThemeLoader } from "./registry.ts"
import type { Theme } from "./types.ts"

const importTheme = (path: string): Promise<Partial<Theme>> =>
  import(`#assets/themes/${path}.json`, { with: { type: "json" } }).then(
    (m) => m.default as Partial<Theme>
  )

/**
 * Async loader map for every built-in theme. Each entry returns the
 * raw JSON; `themes/index.ts` wraps these with `resolveTheme` to
 * produce a fully-resolved `Theme` from the registry. Bundlers
 * code-split each `import("…json")` into its own chunk, so apps only
 * pull the theme they actually load.
 *
 * `as const satisfies Record<string, ThemeLoader>` keeps the keys
 * narrow (so `BuiltinThemeName` is a literal union) but lets the
 * value type widen to `Partial<Theme>` — themes have no per-key
 * narrow types worth preserving, and the satisfies clause means
 * `themes/index.ts` can pass this map straight to `themeRegistry`
 * with no cast.
 */
export const builtin = {
  "ayu-dark": () => importTheme("ayu-dark"),
  "catppuccin-frappe": () => importTheme("catppuccin-frappe"),
  "catppuccin-latte": () => importTheme("catppuccin-latte"),
  "catppuccin-macchiato": () => importTheme("catppuccin-macchiato"),
  "catppuccin-mocha": () => importTheme("catppuccin-mocha"),
  dracula: () => importTheme("dracula"),
  "dracula-soft": () => importTheme("dracula-soft"),
  "everforest-dark": () => importTheme("everforest-dark"),
  "everforest-light": () => importTheme("everforest-light"),
  "github-dark": () => importTheme("github-dark"),
  "github-light": () => importTheme("github-light"),
  "gruvbox-dark-medium": () => importTheme("gruvbox-dark-medium"),
  "kanagawa-dragon": () => importTheme("kanagawa-dragon"),
  "kanagawa-wave": () => importTheme("kanagawa-wave"),
  "material-theme-palenight": () => importTheme("material-theme-palenight"),
  "min-dark": () => importTheme("min-dark"),
  "min-light": () => importTheme("min-light"),
  monokai: () => importTheme("monokai"),
  "night-owl": () => importTheme("night-owl"),
  nord: () => importTheme("nord"),
  "one-dark-pro": () => importTheme("one-dark-pro"),
  "one-light": () => importTheme("one-light"),
  poimandres: () => importTheme("poimandres"),
  "rose-pine": () => importTheme("rose-pine"),
  "solarized-dark": () => importTheme("solarized-dark"),
  "solarized-light": () => importTheme("solarized-light"),
  "synthwave-84": () => importTheme("synthwave-84"),
  "tokyonight-day": () => importTheme("tokyonight-day"),
  "tokyonight-moon": () => importTheme("tokyonight-moon"),
  "tokyonight-night": () => importTheme("tokyonight-night"),
  "tokyonight-storm": () => importTheme("tokyonight-storm"),
  vesper: () => importTheme("vesper"),
  "vitesse-dark": () => importTheme("vitesse-dark"),
  "vitesse-light": () => importTheme("vitesse-light"),
} as const satisfies Record<string, ThemeLoader>
