// Generate `src/themes/builtin.ts` from the JSON files under
// `assets/themes/`. The result is a flat loader map; each entry is a
// dynamic import of the JSON, so any modern bundler code-splits each
// theme into its own chunk loaded on demand.
//
// Loaders deliberately don't call `resolveTheme` here — that step lives
// in `themes/index.ts` so this file stays purely mechanical and the
// generator never has to know about the Theme shape. Idempotent.

import { readdirSync, writeFileSync } from "node:fs"
import { basename } from "node:path"

const ASSET_DIR = "assets/themes"
const OUT_FILE = "src/themes/builtin.ts"

const header = `// AUTO-GENERATED by \`scripts/gen-themes.ts\`. DO NOT EDIT.\n// Re-run \`bun scripts/gen-themes.ts\` after adding/renaming a theme.\n\n`

function genBuiltin(names: readonly string[]): string {
  // Per-loader `as Partial<Theme>` is needed because the JSON modules
  // infer literal types with extras like `$schema` that don't strictly
  // extend `Partial<Theme>`. Casting at the load site keeps the const's
  // outer shape clean — `as const satisfies LoaderMap<…>` then verifies
  // the whole thing without complaining about excess properties.
  const entries = names.map((n) => `  "${n}": () => importTheme("${n}"),`).join("\n")

  return `${header}import type { ThemeLoader } from "./registry.ts"
import type { Theme } from "./types.ts"

const importTheme = (path: string): Promise<Partial<Theme>> =>
  import(\`#assets/themes/\${path}.json\`, { with: { type: "json" } }).then((m) => m.default as Partial<Theme>)

/**
 * Async loader map for every built-in theme. Each entry returns the
 * raw JSON; \`themes/index.ts\` wraps these with \`resolveTheme\` to
 * produce a fully-resolved \`Theme\` from the registry. Bundlers
 * code-split each \`import("…json")\` into its own chunk, so apps only
 * pull the theme they actually load.
 *
 * \`as const satisfies Record<string, ThemeLoader>\` keeps the keys
 * narrow (so \`BuiltinThemeName\` is a literal union) but lets the
 * value type widen to \`Partial<Theme>\` — themes have no per-key
 * narrow types worth preserving, and the satisfies clause means
 * \`themes/index.ts\` can pass this map straight to \`themeRegistry\`
 * with no cast.
 */
export const builtin = {
${entries}
} as const satisfies Record<string, ThemeLoader>
`
}

function main(): void {
  const names = readdirSync(ASSET_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => basename(f, ".json"))
    .toSorted()

  writeFileSync(OUT_FILE, genBuiltin(names))

  console.log(`✔  wrote ${names.length} entries to ${OUT_FILE}`)
}

main()
